"""FAULT_NARRATIVE_FACTS: one small set of ground-truth scenario facts per executable
fault_id, keyed to exactly the fields Job A (desk/reason, Phase 4) is meant to extract
from a customer's free-text report -- scope, onset, a recent change the customer is aware
of (or not), what they already tried, who's reporting it, and, for the
confident-misdiagnosis narrative register, a wrong belief the customer holds about the
cause. This file is the ground truth those extractions get graded against; the five
render_<register>() functions in registers.py turn one fact set into five differently-
worded customer reports without changing the underlying facts.

Directly authored, not model-generated -- no Gemini/Ollama call produced any word here.
That is a deliberate, stated choice for this phase (see docs/PHASE3_NOTES.md), not an
oversight: freezing hand-written facts now means Phase 4's Job A eval has a stable target
that doesn't shift if the narrative text is ever regenerated by a model later.

sha1_signature_downgrade has no entry: it's DOCUMENTED_GAP with no executable case and no
artifacts, so there is nothing for a customer to have reported.

Three further entries below (withheld_cert, withheld_clock, duplicate_role_attributes)
cover harness/faults/ambiguous.py and harness/faults/conflicting.py -- kept out of
ALL_FAULTS but still real corpus cases a customer would have opened a ticket about, so
Job A needs something to read for them too. 19 + 3 = 22 total entries.
"""

from __future__ import annotations

from typing import TypedDict


class NarrativeFacts(TypedDict, total=False):
    scope: str  # all_users | subset | single_user | new_users_only
    onset: str  # relative, customer's own words for "when"
    recent_change: str | None
    already_tried: list[str]
    reporter_role: str
    wrong_belief: str | None  # what the customer confidently but incorrectly blames


FAULT_NARRATIVE_FACTS: dict[str, NarrativeFacts] = {
    "cert_rotation": {
        "scope": "all_users",
        "onset": "since this morning",
        "recent_change": "our identity team rotated a signing certificate over the weekend",
        "already_tried": ["had a few people clear cookies and retry"],
        "reporter_role": "IT admin",
        "wrong_belief": "our network firewall is blocking the login page",
    },
    "cert_expired": {
        "scope": "all_users",
        "onset": "starting today",
        "recent_change": None,
        "already_tried": ["restarted the identity server", "asked two users to try a different browser"],
        "reporter_role": "IT admin",
        "wrong_belief": "your platform pushed an update that broke something",
    },
    "wrong_audience": {
        "scope": "all_users",
        "onset": "ever since we finished setup last week",
        "recent_change": "we just finished configuring SSO for the first time",
        "already_tried": ["double-checked the login URL"],
        "reporter_role": "IT admin",
        "wrong_belief": "we must have the wrong login URL",
    },
    "acs_url_trailing_slash": {
        "scope": "all_users",
        "onset": "since we updated our SSO config yesterday",
        "recent_change": "updated the app's URL in our identity provider console yesterday",
        "already_tried": ["re-typed the URL twice to be sure"],
        "reporter_role": "IT admin",
        "wrong_belief": "there must be a typo somewhere in your onboarding docs",
    },
    "http_https_mismatch": {
        "scope": "subset",
        "onset": "for some of our users, not all",
        "recent_change": "we recently moved everything behind our new load balancer",
        "already_tried": ["confirmed the affected users are on our new network segment"],
        "reporter_role": "IT admin",
        "wrong_belief": "it's a caching issue on your end",
    },
    "destination_mismatch": {
        "scope": "all_users",
        "onset": "since this morning",
        "recent_change": "migrated to a new SSO app registration this week",
        "already_tried": ["compared the old and new config side by side but couldn't spot it"],
        "reporter_role": "IT admin",
        "wrong_belief": "the migration must not have finished on your side",
    },
    "wrong_issuer": {
        "scope": "new_users_only",
        "onset": "for anyone we've added since last week",
        "recent_change": "stood up a second identity environment for testing",
        "already_tried": ["confirmed existing users still log in fine"],
        "reporter_role": "IT admin",
        "wrong_belief": "your system must be caching an old list of allowed users",
    },
    "clock_skew": {
        "scope": "single_user",
        "onset": "just for one user, since yesterday",
        "recent_change": None,
        "already_tried": ["had the user restart their laptop"],
        "reporter_role": "IT admin",
        "wrong_belief": "their account must be corrupted somehow",
    },
    "assertion_expired": {
        "scope": "subset",
        "onset": "intermittently, a few times a day",
        "recent_change": None,
        "already_tried": ["asked affected users to log in again, which usually works"],
        "reporter_role": "support engineer (internal, escalated from a customer)",
        "wrong_belief": "it feels like a random timeout bug in your app",
    },
    "inresponseto_mismatch": {
        "scope": "subset",
        "onset": "randomly, a handful of times this week",
        "recent_change": "rolled out a new internal proxy in front of our identity provider",
        "already_tried": ["confirmed it's not the same users every time"],
        "reporter_role": "IT admin",
        "wrong_belief": "our proxy vendor says it's not on their end",
    },
    "broken_signature": {
        "scope": "all_users",
        "onset": "since around 2pm today",
        "recent_change": "our security team pushed a WAF rule change this afternoon",
        "already_tried": ["rolled back the WAF change partially, still broken"],
        "reporter_role": "IT admin",
        "wrong_belief": "your service must be having an outage",
    },
    "missing_nameid": {
        "scope": "subset",
        "onset": "for a handful of users since a directory sync last night",
        "recent_change": "ran a bulk user directory sync last night",
        "already_tried": ["manually re-added one affected user, no change"],
        "reporter_role": "IT admin",
        "wrong_belief": "those specific user accounts must be broken on your side",
    },
    "unsupported_nameid_format": {
        "scope": "all_users",
        "onset": "since we switched identity providers this week",
        "recent_change": "migrated from our old identity provider to a new one",
        "already_tried": ["re-read your SSO setup guide twice"],
        "reporter_role": "IT admin",
        "wrong_belief": "your integration must not support our new provider at all",
    },
    "encrypted_assertion": {
        "scope": "all_users",
        "onset": "since our security review changes went live",
        "recent_change": "our security team required assertion encryption to be turned on",
        "already_tried": ["confirmed the encryption setting looks correct on our side"],
        "reporter_role": "IT admin",
        "wrong_belief": "you must not support encrypted assertions at all",
    },
    "truncated_response": {
        "scope": "subset",
        "onset": "intermittently, seems to depend on the user",
        "recent_change": None,
        "already_tried": ["noticed it happens more for users on our VPN"],
        "reporter_role": "IT admin",
        "wrong_belief": "our VPN must be the problem, but our network team says it's fine",
    },
    "double_encoded_response": {
        "scope": "all_users",
        "onset": "since we upgraded our reverse proxy last night",
        "recent_change": "upgraded our reverse proxy software last night",
        "already_tried": ["rolled the proxy upgrade back on one node, still broken there too"],
        "reporter_role": "IT admin",
        "wrong_belief": "the proxy upgrade release notes don't mention SSO at all so it can't be that",
    },
    "stripped_relaystate": {
        "scope": "all_users",
        "onset": "for the last few days",
        "recent_change": None,
        "already_tried": ["confirmed login itself succeeds, just lands somewhere wrong"],
        "reporter_role": "end user",
        "wrong_belief": "your app must have a broken bookmark or redirect somewhere",
    },
    "wrong_binding": {
        "scope": "all_users",
        "onset": "since we changed our identity provider's SSO settings",
        "recent_change": "an admin changed a binding/protocol setting while cleaning up our SSO config",
        "already_tried": ["reverted a couple of other settings, this one's still broken"],
        "reporter_role": "IT admin",
        "wrong_belief": "your login page must be down",
    },
    "negative_control": {
        "scope": "single_user",
        "onset": "right now, just for me",
        "recent_change": None,
        "already_tried": ["tried logging in three times", "checked caps lock"],
        "reporter_role": "end user",
        "wrong_belief": "your website must be broken",
    },
    "withheld_cert": {
        "scope": "all_users",
        "onset": "since we turned SSO on",
        "recent_change": "just finished our initial SSO setup on our end",
        "already_tried": ["re-checked our entity ID and ACS URL twice"],
        "reporter_role": "IT admin",
        "wrong_belief": "our config must have a typo somewhere",
    },
    "withheld_clock": {
        "scope": "single_user",
        "onset": "on and off for one user this week",
        "recent_change": None,
        "already_tried": ["had the user re-sync their laptop clock, unsure if it helped"],
        "reporter_role": "IT admin",
        "wrong_belief": "it must be that specific user's browser cache",
    },
    "duplicate_role_attributes": {
        "scope": "subset",
        "onset": "we noticed it over the past week or so",
        "recent_change": "an admin cleaned up some group-to-role mappings in our directory",
        "already_tried": ["spot-checked a couple of affected accounts in our directory, looked normal there"],
        "reporter_role": "IT admin",
        "wrong_belief": "some of our users must just have stale permissions cached on your side",
    },
}
